### ISSUE TITLE
Error on npm run watch

### ISSUE THREAD

**Issue by kutzi** [rauschma/webpack-es6-demo#2]
When I run it, I get:

> npm run watch
> 
> webpack-es6-demo@1.0.0 watch /home/kutzi/conferences/webpack-es6-demo
> webpack --watch

Hash: 396f0bfb9d565b6f60f0
Version: webpack 1.12.2
Time: 420ms
    + 1 hidden modules

ERROR in ./es6/main.js
Module parse failed: /home/kutzi/conferences/webpack-es6-demo/node_modules/babel-loader/index.js!/home/kutzi/conferences/webpack-es6-demo/es6/main.js Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import Point from './Point.js';
| var body = document.querySelector('body');
| body.textContent = 'Good point: ' + new Point(1, 23);

**Comment by rauschma** [comment]
Fixed now, thanks for reporting this!
